// Generated by: main
// TypeWriter: smallset
// Directive: +gen on Thing

package main

import (
	"bytes"
	"fmt"
)

/*
The MIT License (MIT)

Copyright (c) 2016 Xuanyi Chew (chewxy [AT] gmail.com)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

//ThingSet is a set of Thing
type ThingSet []Thing

// NewThingSet does what it says on the tin
func NewThingSet(a ...Thing) ThingSet {
	var set ThingSet

	for _, v := range a {
		set = set.Add(v)
	}

	return set
}

// ToSlice returns the elements of the current set as a slice
func (set ThingSet) ToSlice() []Thing {
	return []Thing(set)
}

// Determines if items are already in set
func (set ThingSet) ContainsAll(ws ...Thing) bool {
	for _, w := range ws {
		if !set.Contains(w) {
			return false
		}
	}
	return true
}

// Add... ditto
func (set ThingSet) Add(item Thing) ThingSet {
	if set.Contains(item) {
		return set
	}
	set = append(set, item)
	return set
}

//Is the other set a subset of this set?
func (set ThingSet) IsSubsetOf(other ThingSet) bool {
	if len(set) > len(other) {
		return false
	}

	for _, v := range set {
		if !other.Contains(v) {
			return false
		}
	}

	return true
}

// Is the other set a super set of this set?
func (set ThingSet) IsSupersetOf(other ThingSet) bool {
	return other.IsSubsetOf(set)
}

// Intersect
func (set ThingSet) Intersect(other ThingSet) ThingSet {
	retVal := make(ThingSet, 0)
	for _, o := range other {
		if set.Contains(o) {
			retVal = append(retVal, o)
		}
	}
	return retVal
}

//Union
func (set ThingSet) Union(other ThingSet) ThingSet {
	retVal := make(ThingSet, len(set))
	copy(retVal, set)
	for _, o := range other {
		if !retVal.Contains(o) {
			retVal = append(retVal, o)
		}
	}
	return retVal
}

// Returns a new set with items in the current set but not in the other set.
// Equivalent to  (set - other)
func (set ThingSet) Difference(other ThingSet) ThingSet {
	retVal := make(ThingSet, 0)
	for _, v := range set {
		if !other.Contains(v) {
			retVal = append(retVal, v)
		}
	}
	return retVal
}

// Equivalent to
func (set ThingSet) SymmetricDifference(other ThingSet) ThingSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Equality... does what it says on the tin
func (set ThingSet) Equals(other ThingSet) bool {
	if len(set) != len(other) {
		return false
	}

	for _, v := range set {
		if !other.Contains(v) {
			return false
		}
	}

	return true
}

// String for stuff
func (set ThingSet) String() string {
	var buf bytes.Buffer
	buf.WriteString("ThingSet[")
	for i, v := range set {
		if i == len(set)-1 {
			fmt.Fprintf(&buf, "%v", v)
		} else {
			fmt.Fprintf(&buf, "%v, ", v)
		}
	}
	buf.WriteString("]")
	return buf.String()
}

// Determines if an item is in the set already
func (set ThingSet) Contains(w Thing) bool {
	for _, v := range set {
		if v == w {
			return true
		}
	}
	return false
}
